name: Continuous Delivery

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
          POSTGRES_PORT: ${{ secrets.DB_PORT }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cov=app --cov-report=xml --cov-report=term-missing
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
          DB_PORT: ${{ secrets.DB_PORT }}
      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@v1.1.47
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
